name: 🔑 Get Unity License File (ALF)

on: workflow_dispatch

jobs:
  DoSomething:
    name: Um Job Legal
    runs-on: ubuntu-latest
    container:
      image: "unityci/editor:ubuntu-2019.4.17f1-base-0.15.0"
    steps:
    - uses: actions/checkout@v2
    - run: /opt/unity/Editor/Unity -nographics -batchmode -createManualActivationFile -logfile || true
    - uses: actions/upload-artifact@v2
      with:
        path: Unity_v2019.4.17f1.alf
