name: Tests

on: push

env:
  UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}

jobs:
  EditModeTestRunner:
    name: Edit Mode Tests
    runs-on: ubuntu-latest
    container:
      image: "unityci/editor:ubuntu-2021.3.10f1-base-2.0.0"
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2
    - name: Activate Unity
      run: echo "$UNITY_LICENSE" > Unity_lic.ulf && (/opt/unity/Editor/Unity -nographics -batchmode -manualLicenseFile Unity_lic.ulf || true)
    - name: Run Edit Mode Tests
      run: /opt/unity/Editor/Unity -projectPath . -batchmode -nographics -runEditorTests -editorTestsResultFile test-results.xml
    - name: Publish Results
      uses: actions/upload-artifact@v2
      with:
        path: test-results.xml